# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160916_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
