# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20160917_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
    ]
