# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20160917_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
