# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20160917_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
